"""initial schema clean baseline

Revision ID: 0001_initial
Revises: 
Create Date: 2026-04-20 08:45:02.272511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_access_policy_action'), 'access_policy', ['action'], unique=False)
    op.create_index(op.f('ix_access_policy_is_deleted'), 'access_policy', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_access_policy_resource'), 'access_policy', ['resource'], unique=False)
    op.create_index(op.f('ix_access_policy_subject'), 'access_policy', ['subject'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gc_org_id', sa.Integer(), nullable=True),
    sa.Column('name_fr', sa.String(length=128), nullable=True),
    sa.Column('abbreviation', sa.String(length=16), nullable=True),
    sa.Column('abbreviation_fr', sa.String(length=16), nullable=True),
    sa.Column('lead_department_name', sa.String(length=64), nullable=True),
    sa.Column('lead_department_name_fr', sa.String(length=192), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_department_gc_org_id'), 'department', ['gc_org_id'], unique=True)
    op.create_index(op.f('ix_department_is_deleted'), 'department', ['is_deleted'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('tier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('rate_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_rate_limit_tier_id'), 'rate_limit', ['tier_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('role_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_auth_subject'), 'user', ['auth_subject'], unique=True)
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_enabled'), 'user', ['enabled'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_tier_id'), 'user', ['tier_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_workspace_department_id'), 'workspace', ['department_id'], unique=False)
    op.create_index(op.f('ix_workspace_is_deleted'), 'workspace', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=False)
    op.create_table('application_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('about_application', sa.Text(), nullable=False),
    sa.Column('program_line_of_business', sa.String(length=255), nullable=False),
    sa.Column('application_url', sa.String(length=500), nullable=False),
    sa.Column('application_description', sa.Text(), nullable=False),
    sa.Column('technology', sa.String(length=255), nullable=False),
    sa.Column('authentication_protocol', sa.String(length=100), nullable=False),
    sa.Column('tech_stack', sa.Text(), nullable=False),
    sa.Column('rollback_strategy', sa.Text(), nullable=False),
    sa.Column('credential_assurance_level', sa.String(length=100), nullable=False),
    sa.Column('identity_assurance_level', sa.String(length=100), nullable=False),
    sa.Column('identity_proofing_method', sa.String(length=255), nullable=False),
    sa.Column('authority_to_collect_personal_information', sa.Text(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('portal_name', sa.String(length=255), nullable=True),
    sa.Column('planned_oidc_implementation_date', sa.String(length=100), nullable=True),
    sa.Column('requests_profile_data_pushes', sa.Boolean(), nullable=False),
    sa.Column('has_access_management_layer', sa.Boolean(), nullable=False),
    sa.Column('identity_proofing_method_other', sa.Text(), nullable=True),
    sa.Column('is_cbas', sa.Boolean(), nullable=False),
    sa.Column('has_account_recovery', sa.Boolean(), nullable=False),
    sa.Column('has_privacy_notice', sa.Boolean(), nullable=False),
    sa.Column('user_types', sa.JSON(), nullable=False),
    sa.Column('user_type_other', sa.Text(), nullable=True),
    sa.Column('monthly_active_users', sa.Integer(), nullable=True),
    sa.Column('peak_usage_periods', sa.Text(), nullable=True),
    sa.Column('personal_information_collected', sa.JSON(), nullable=False),
    sa.Column('personal_information_other', sa.Text(), nullable=True),
    sa.Column('current_sign_in_options', sa.JSON(), nullable=False),
    sa.Column('current_sign_in_options_other', sa.Text(), nullable=True),
    sa.Column('consolidator_used', sa.String(length=255), nullable=True),
    sa.Column('current_mfa_options', sa.String(length=255), nullable=True),
    sa.Column('uses_canadalogin_migration', sa.Boolean(), nullable=False),
    sa.Column('migration_rationale', sa.Text(), nullable=True),
    sa.Column('schedule_blackout_periods', sa.Text(), nullable=True),
    sa.Column('transition_risks', sa.Text(), nullable=True),
    sa.Column('transition_mitigations', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_application_info_is_deleted'), 'application_info', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_application_info_workspace_id'), 'application_info', ['workspace_id'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_workspace_member_is_deleted'), 'workspace_member', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('application_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_info_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title_role', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('alternate_phone_number', sa.String(length=50), nullable=True),
    sa.Column('contact_type', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('contact_roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_info_id'], ['application_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_application_contact_application_info_id'), 'application_contact', ['application_info_id'], unique=False)
    op.create_index(op.f('ix_application_contact_is_deleted'), 'application_contact', ['is_deleted'], unique=False)
    op.create_table('rp_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('application_info_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('ibm_sv_application_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_info_id'], ['application_info.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_rp_application_application_info_id'), 'rp_application', ['application_info_id'], unique=True)
    op.create_index(op.f('ix_rp_application_ibm_sv_application_id'), 'rp_application', ['ibm_sv_application_id'], unique=False)
    op.create_index(op.f('ix_rp_application_is_deleted'), 'rp_application', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rp_application_workspace_id'), 'rp_application', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rp_application_workspace_id'), table_name='rp_application')
    op.drop_index(op.f('ix_rp_application_is_deleted'), table_name='rp_application')
    op.drop_index(op.f('ix_rp_application_ibm_sv_application_id'), table_name='rp_application')
    op.drop_index(op.f('ix_rp_application_application_info_id'), table_name='rp_application')
    op.drop_table('rp_application')
    op.drop_index(op.f('ix_application_contact_is_deleted'), table_name='application_contact')
    op.drop_index(op.f('ix_application_contact_application_info_id'), table_name='application_contact')
    op.drop_table('application_contact')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_is_deleted'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_application_info_workspace_id'), table_name='application_info')
    op.drop_index(op.f('ix_application_info_is_deleted'), table_name='application_info')
    op.drop_table('application_info')
    op.drop_index(op.f('ix_workspace_slug'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_is_deleted'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_department_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_tier_id'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_enabled'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_index(op.f('ix_user_auth_subject'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rate_limit_tier_id'), table_name='rate_limit')
    op.drop_table('rate_limit')
    op.drop_table('tier')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_is_deleted'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_department_is_deleted'), table_name='department')
    op.drop_index(op.f('ix_department_gc_org_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_access_policy_subject'), table_name='access_policy')
    op.drop_index(op.f('ix_access_policy_resource'), table_name='access_policy')
    op.drop_index(op.f('ix_access_policy_is_deleted'), table_name='access_policy')
    op.drop_index(op.f('ix_access_policy_action'), table_name='access_policy')
    op.drop_table('access_policy')
    # ### end Alembic commands ###
