/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OptionalHolidaysRouteImport } from './routes/optional-holidays'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FederalAndProvincialHolidaysRouteImport } from './routes/federal-and-provincial-holidays'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthCompleteRouteImport } from './routes/auth-complete'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSetupRouteImport } from './routes/profile/setup'
import { Route as RpApplicationsMineRpApplicationUuidRouteImport } from './routes/rp-applications/mine/$rpApplicationUuid'
import { Route as RpApplicationsMineRpApplicationUuidIndexRouteImport } from './routes/rp-applications/mine/$rpApplicationUuid/index'
import { Route as RpApplicationsMineRpApplicationUuidMauReportRouteImport } from './routes/rp-applications/mine/$rpApplicationUuid/mau-report'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionalHolidaysRoute = OptionalHolidaysRouteImport.update({
  id: '/optional-holidays',
  path: '/optional-holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FederalAndProvincialHolidaysRoute =
  FederalAndProvincialHolidaysRouteImport.update({
    id: '/federal-and-provincial-holidays',
    path: '/federal-and-provincial-holidays',
    getParentRoute: () => rootRouteImport,
  } as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth-complete',
  path: '/auth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RpApplicationsMineRpApplicationUuidRoute =
  RpApplicationsMineRpApplicationUuidRouteImport.update({
    id: '/rp-applications/mine/$rpApplicationUuid',
    path: '/rp-applications/mine/$rpApplicationUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const RpApplicationsMineRpApplicationUuidIndexRoute =
  RpApplicationsMineRpApplicationUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RpApplicationsMineRpApplicationUuidRoute,
  } as any)
const RpApplicationsMineRpApplicationUuidMauReportRoute =
  RpApplicationsMineRpApplicationUuidMauReportRouteImport.update({
    id: '/mau-report',
    path: '/mau-report',
    getParentRoute: () => RpApplicationsMineRpApplicationUuidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/rp-applications/mine/$rpApplicationUuid': typeof RpApplicationsMineRpApplicationUuidRouteWithChildren
  '/rp-applications/mine/$rpApplicationUuid/mau-report': typeof RpApplicationsMineRpApplicationUuidMauReportRoute
  '/rp-applications/mine/$rpApplicationUuid/': typeof RpApplicationsMineRpApplicationUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/rp-applications/mine/$rpApplicationUuid/mau-report': typeof RpApplicationsMineRpApplicationUuidMauReportRoute
  '/rp-applications/mine/$rpApplicationUuid': typeof RpApplicationsMineRpApplicationUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/rp-applications/mine/$rpApplicationUuid': typeof RpApplicationsMineRpApplicationUuidRouteWithChildren
  '/rp-applications/mine/$rpApplicationUuid/mau-report': typeof RpApplicationsMineRpApplicationUuidMauReportRoute
  '/rp-applications/mine/$rpApplicationUuid/': typeof RpApplicationsMineRpApplicationUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access-denied'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/error'
    | '/federal-and-provincial-holidays'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/roles'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/profile/setup'
    | '/rp-applications/mine/$rpApplicationUuid'
    | '/rp-applications/mine/$rpApplicationUuid/mau-report'
    | '/rp-applications/mine/$rpApplicationUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access-denied'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/error'
    | '/federal-and-provincial-holidays'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/roles'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/profile/setup'
    | '/rp-applications/mine/$rpApplicationUuid/mau-report'
    | '/rp-applications/mine/$rpApplicationUuid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access-denied'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/error'
    | '/federal-and-provincial-holidays'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/roles'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/profile/setup'
    | '/rp-applications/mine/$rpApplicationUuid'
    | '/rp-applications/mine/$rpApplicationUuid/mau-report'
    | '/rp-applications/mine/$rpApplicationUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ErrorRoute: typeof ErrorRoute
  FederalAndProvincialHolidaysRoute: typeof FederalAndProvincialHolidaysRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OptionalHolidaysRoute: typeof OptionalHolidaysRoute
  PoliciesRoute: typeof PoliciesRoute
  RolesRoute: typeof RolesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TiersRoute: typeof TiersRoute
  UsersRoute: typeof UsersRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RpApplicationsMineRpApplicationUuidRoute: typeof RpApplicationsMineRpApplicationUuidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optional-holidays': {
      id: '/optional-holidays'
      path: '/optional-holidays'
      fullPath: '/optional-holidays'
      preLoaderRoute: typeof OptionalHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federal-and-provincial-holidays': {
      id: '/federal-and-provincial-holidays'
      path: '/federal-and-provincial-holidays'
      fullPath: '/federal-and-provincial-holidays'
      preLoaderRoute: typeof FederalAndProvincialHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete': {
      id: '/auth-complete'
      path: '/auth-complete'
      fullPath: '/auth-complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rp-applications/mine/$rpApplicationUuid': {
      id: '/rp-applications/mine/$rpApplicationUuid'
      path: '/rp-applications/mine/$rpApplicationUuid'
      fullPath: '/rp-applications/mine/$rpApplicationUuid'
      preLoaderRoute: typeof RpApplicationsMineRpApplicationUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rp-applications/mine/$rpApplicationUuid/': {
      id: '/rp-applications/mine/$rpApplicationUuid/'
      path: '/'
      fullPath: '/rp-applications/mine/$rpApplicationUuid/'
      preLoaderRoute: typeof RpApplicationsMineRpApplicationUuidIndexRouteImport
      parentRoute: typeof RpApplicationsMineRpApplicationUuidRoute
    }
    '/rp-applications/mine/$rpApplicationUuid/mau-report': {
      id: '/rp-applications/mine/$rpApplicationUuid/mau-report'
      path: '/mau-report'
      fullPath: '/rp-applications/mine/$rpApplicationUuid/mau-report'
      preLoaderRoute: typeof RpApplicationsMineRpApplicationUuidMauReportRouteImport
      parentRoute: typeof RpApplicationsMineRpApplicationUuidRoute
    }
  }
}

interface RpApplicationsMineRpApplicationUuidRouteChildren {
  RpApplicationsMineRpApplicationUuidMauReportRoute: typeof RpApplicationsMineRpApplicationUuidMauReportRoute
  RpApplicationsMineRpApplicationUuidIndexRoute: typeof RpApplicationsMineRpApplicationUuidIndexRoute
}

const RpApplicationsMineRpApplicationUuidRouteChildren: RpApplicationsMineRpApplicationUuidRouteChildren =
  {
    RpApplicationsMineRpApplicationUuidMauReportRoute:
      RpApplicationsMineRpApplicationUuidMauReportRoute,
    RpApplicationsMineRpApplicationUuidIndexRoute:
      RpApplicationsMineRpApplicationUuidIndexRoute,
  }

const RpApplicationsMineRpApplicationUuidRouteWithChildren =
  RpApplicationsMineRpApplicationUuidRoute._addFileChildren(
    RpApplicationsMineRpApplicationUuidRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  ErrorRoute: ErrorRoute,
  FederalAndProvincialHolidaysRoute: FederalAndProvincialHolidaysRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OptionalHolidaysRoute: OptionalHolidaysRoute,
  PoliciesRoute: PoliciesRoute,
  RolesRoute: RolesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TiersRoute: TiersRoute,
  UsersRoute: UsersRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RpApplicationsMineRpApplicationUuidRoute:
    RpApplicationsMineRpApplicationUuidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
