/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourApplicationsRouteImport } from './routes/your-applications'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OnboardingOversightRouteImport } from './routes/onboarding-oversight'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AuthCompleteRouteImport } from './routes/auth-complete'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YourApplicationsIndexRouteImport } from './routes/your-applications/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as OnboardingOversightIndexRouteImport } from './routes/onboarding-oversight/index'
import { Route as YourApplicationsRpApplicationUuidRouteImport } from './routes/your-applications/$rpApplicationUuid'
import { Route as WorkspacesRpRegistrationAdoptionRouteImport } from './routes/workspaces/rp-registration-adoption'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WorkspacesWorkspaceUuidRouteImport } from './routes/workspaces/$workspaceUuid'
import { Route as UsersInviteRouteImport } from './routes/users/invite'
import { Route as UsersUserUuidRouteImport } from './routes/users/$userUuid'
import { Route as ReportsWorkspacesRouteImport } from './routes/reports/workspaces'
import { Route as ReportsApplicationsRouteImport } from './routes/reports/applications'
import { Route as ProfileSetupRouteImport } from './routes/profile/setup'
import { Route as OnboardingOversightReportsRouteImport } from './routes/onboarding-oversight/reports'
import { Route as OnboardingOversightQueueRouteImport } from './routes/onboarding-oversight/queue'
import { Route as InvitationsRpApplicationsRouteImport } from './routes/invitations/rp-applications'
import { Route as YourApplicationsRpApplicationUuidIndexRouteImport } from './routes/your-applications/$rpApplicationUuid/index'
import { Route as WorkspacesRpRegistrationAdoptionIndexRouteImport } from './routes/workspaces/rp-registration-adoption/index'
import { Route as WorkspacesWorkspaceUuidIndexRouteImport } from './routes/workspaces/$workspaceUuid/index'
import { Route as InvitationsRpApplicationsIndexRouteImport } from './routes/invitations/rp-applications/index'
import { Route as YourApplicationsRpApplicationUuidMauReportRouteImport } from './routes/your-applications/$rpApplicationUuid/mau-report'
import { Route as YourApplicationsRpApplicationUuidManageCredentialsRouteImport } from './routes/your-applications/$rpApplicationUuid/manage-credentials'
import { Route as YourApplicationsRpApplicationUuidDepartmentSetupRouteImport } from './routes/your-applications/$rpApplicationUuid/department-setup'
import { Route as WorkspacesRpRegistrationAdoptionRpApplicationUuidRouteImport } from './routes/workspaces/rp-registration-adoption/$rpApplicationUuid'
import { Route as WorkspacesWorkspaceUuidSettingsRouteImport } from './routes/workspaces/$workspaceUuid/settings'
import { Route as WorkspacesWorkspaceUuidReportsRouteImport } from './routes/workspaces/$workspaceUuid/reports'
import { Route as WorkspacesWorkspaceUuidMembersRouteImport } from './routes/workspaces/$workspaceUuid/members'
import { Route as WorkspacesWorkspaceUuidApplicationsRouteImport } from './routes/workspaces/$workspaceUuid/applications'
import { Route as WorkspacesWorkspaceUuidApplicationInformationRouteImport } from './routes/workspaces/$workspaceUuid/application-information'
import { Route as WorkspacesWorkspaceUuidAccessRouteImport } from './routes/workspaces/$workspaceUuid/access'
import { Route as InvitationsRpApplicationsTokenRouteImport } from './routes/invitations/rp-applications/$token'
import { Route as WorkspacesWorkspaceUuidApplicationsIndexRouteImport } from './routes/workspaces/$workspaceUuid/applications/index'
import { Route as WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport } from './routes/workspaces/$workspaceUuid/application-information/index'
import { Route as WorkspacesWorkspaceUuidApplicationsNewRouteImport } from './routes/workspaces/$workspaceUuid/applications/new'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
import { Route as WorkspacesWorkspaceUuidApplicationInformationNewRouteImport } from './routes/workspaces/$workspaceUuid/application-information/new'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/index'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/index'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
import { Route as WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRouteImport } from './routes/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'

const YourApplicationsRoute = YourApplicationsRouteImport.update({
  id: '/your-applications',
  path: '/your-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOversightRoute = OnboardingOversightRouteImport.update({
  id: '/onboarding-oversight',
  path: '/onboarding-oversight',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth-complete',
  path: '/auth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YourApplicationsIndexRoute = YourApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YourApplicationsRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const OnboardingOversightIndexRoute =
  OnboardingOversightIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OnboardingOversightRoute,
  } as any)
const YourApplicationsRpApplicationUuidRoute =
  YourApplicationsRpApplicationUuidRouteImport.update({
    id: '/$rpApplicationUuid',
    path: '/$rpApplicationUuid',
    getParentRoute: () => YourApplicationsRoute,
  } as any)
const WorkspacesRpRegistrationAdoptionRoute =
  WorkspacesRpRegistrationAdoptionRouteImport.update({
    id: '/rp-registration-adoption',
    path: '/rp-registration-adoption',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceUuidRoute = WorkspacesWorkspaceUuidRouteImport.update({
  id: '/$workspaceUuid',
  path: '/$workspaceUuid',
  getParentRoute: () => WorkspacesRoute,
} as any)
const UsersInviteRoute = UsersInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => UsersRoute,
} as any)
const UsersUserUuidRoute = UsersUserUuidRouteImport.update({
  id: '/$userUuid',
  path: '/$userUuid',
  getParentRoute: () => UsersRoute,
} as any)
const ReportsWorkspacesRoute = ReportsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsApplicationsRoute = ReportsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ReportsRoute,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOversightReportsRoute =
  OnboardingOversightReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => OnboardingOversightRoute,
  } as any)
const OnboardingOversightQueueRoute =
  OnboardingOversightQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => OnboardingOversightRoute,
  } as any)
const InvitationsRpApplicationsRoute =
  InvitationsRpApplicationsRouteImport.update({
    id: '/rp-applications',
    path: '/rp-applications',
    getParentRoute: () => InvitationsRoute,
  } as any)
const YourApplicationsRpApplicationUuidIndexRoute =
  YourApplicationsRpApplicationUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesRpRegistrationAdoptionIndexRoute =
  WorkspacesRpRegistrationAdoptionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesRpRegistrationAdoptionRoute,
  } as any)
const WorkspacesWorkspaceUuidIndexRoute =
  WorkspacesWorkspaceUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const InvitationsRpApplicationsIndexRoute =
  InvitationsRpApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InvitationsRpApplicationsRoute,
  } as any)
const YourApplicationsRpApplicationUuidMauReportRoute =
  YourApplicationsRpApplicationUuidMauReportRouteImport.update({
    id: '/mau-report',
    path: '/mau-report',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidManageCredentialsRoute =
  YourApplicationsRpApplicationUuidManageCredentialsRouteImport.update({
    id: '/manage-credentials',
    path: '/manage-credentials',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidDepartmentSetupRoute =
  YourApplicationsRpApplicationUuidDepartmentSetupRouteImport.update({
    id: '/department-setup',
    path: '/department-setup',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute =
  WorkspacesRpRegistrationAdoptionRpApplicationUuidRouteImport.update({
    id: '/$rpApplicationUuid',
    path: '/$rpApplicationUuid',
    getParentRoute: () => WorkspacesRpRegistrationAdoptionRoute,
  } as any)
const WorkspacesWorkspaceUuidSettingsRoute =
  WorkspacesWorkspaceUuidSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidReportsRoute =
  WorkspacesWorkspaceUuidReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidMembersRoute =
  WorkspacesWorkspaceUuidMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsRoute =
  WorkspacesWorkspaceUuidApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationRoute =
  WorkspacesWorkspaceUuidApplicationInformationRouteImport.update({
    id: '/application-information',
    path: '/application-information',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidAccessRoute =
  WorkspacesWorkspaceUuidAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const InvitationsRpApplicationsTokenRoute =
  InvitationsRpApplicationsTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => InvitationsRpApplicationsRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsIndexRoute =
  WorkspacesWorkspaceUuidApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationsRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationIndexRoute =
  WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsNewRoute =
  WorkspacesWorkspaceUuidApplicationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationsRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteImport.update({
    id: '/$rpApplicationUuid',
    path: '/$rpApplicationUuid',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationsRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationNewRoute =
  WorkspacesWorkspaceUuidApplicationInformationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport.update(
    {
      id: '/$applicationInformationUuid',
      path: '/$applicationInformationUuid',
      getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () =>
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRouteImport.update(
    {
      id: '/manage-credentials',
      path: '/manage-credentials',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRouteImport.update(
    {
      id: '/configuration',
      path: '/configuration',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () =>
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRouteImport.update(
    {
      id: '/registration/confirmation',
      path: '/registration/confirmation',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRouteImport.update(
    {
      id: '/registration/$step',
      path: '/registration/$step',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/administration': typeof AdministrationRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/logout': typeof LogoutRoute
  '/onboarding-oversight': typeof OnboardingOversightRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/invitations/rp-applications': typeof InvitationsRpApplicationsRouteWithChildren
  '/onboarding-oversight/queue': typeof OnboardingOversightQueueRoute
  '/onboarding-oversight/reports': typeof OnboardingOversightReportsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/reports/applications': typeof ReportsApplicationsRoute
  '/reports/workspaces': typeof ReportsWorkspacesRoute
  '/users/$userUuid': typeof UsersUserUuidRoute
  '/users/invite': typeof UsersInviteRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/rp-registration-adoption': typeof WorkspacesRpRegistrationAdoptionRouteWithChildren
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/onboarding-oversight/': typeof OnboardingOversightIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/invitations/rp-applications/$token': typeof InvitationsRpApplicationsTokenRoute
  '/workspaces/$workspaceUuid/access': typeof WorkspacesWorkspaceUuidAccessRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  '/workspaces/$workspaceUuid/applications': typeof WorkspacesWorkspaceUuidApplicationsRouteWithChildren
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/reports': typeof WorkspacesWorkspaceUuidReportsRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/workspaces/rp-registration-adoption/$rpApplicationUuid': typeof WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/invitations/rp-applications/': typeof InvitationsRpApplicationsIndexRoute
  '/workspaces/$workspaceUuid/': typeof WorkspacesWorkspaceUuidIndexRoute
  '/workspaces/rp-registration-adoption/': typeof WorkspacesRpRegistrationAdoptionIndexRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/applications/new': typeof WorkspacesWorkspaceUuidApplicationsNewRoute
  '/workspaces/$workspaceUuid/application-information/': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/applications/': typeof WorkspacesWorkspaceUuidApplicationsIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/administration': typeof AdministrationRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/onboarding-oversight/queue': typeof OnboardingOversightQueueRoute
  '/onboarding-oversight/reports': typeof OnboardingOversightReportsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/reports/applications': typeof ReportsApplicationsRoute
  '/reports/workspaces': typeof ReportsWorkspacesRoute
  '/users/$userUuid': typeof UsersUserUuidRoute
  '/users/invite': typeof UsersInviteRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/onboarding-oversight': typeof OnboardingOversightIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/users': typeof UsersIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/your-applications': typeof YourApplicationsIndexRoute
  '/invitations/rp-applications/$token': typeof InvitationsRpApplicationsTokenRoute
  '/workspaces/$workspaceUuid/access': typeof WorkspacesWorkspaceUuidAccessRoute
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/reports': typeof WorkspacesWorkspaceUuidReportsRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/workspaces/rp-registration-adoption/$rpApplicationUuid': typeof WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/invitations/rp-applications': typeof InvitationsRpApplicationsIndexRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidIndexRoute
  '/workspaces/rp-registration-adoption': typeof WorkspacesRpRegistrationAdoptionIndexRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/applications/new': typeof WorkspacesWorkspaceUuidApplicationsNewRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/applications': typeof WorkspacesWorkspaceUuidApplicationsIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/administration': typeof AdministrationRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/logout': typeof LogoutRoute
  '/onboarding-oversight': typeof OnboardingOversightRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/invitations/rp-applications': typeof InvitationsRpApplicationsRouteWithChildren
  '/onboarding-oversight/queue': typeof OnboardingOversightQueueRoute
  '/onboarding-oversight/reports': typeof OnboardingOversightReportsRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/reports/applications': typeof ReportsApplicationsRoute
  '/reports/workspaces': typeof ReportsWorkspacesRoute
  '/users/$userUuid': typeof UsersUserUuidRoute
  '/users/invite': typeof UsersInviteRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/rp-registration-adoption': typeof WorkspacesRpRegistrationAdoptionRouteWithChildren
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/onboarding-oversight/': typeof OnboardingOversightIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/invitations/rp-applications/$token': typeof InvitationsRpApplicationsTokenRoute
  '/workspaces/$workspaceUuid/access': typeof WorkspacesWorkspaceUuidAccessRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  '/workspaces/$workspaceUuid/applications': typeof WorkspacesWorkspaceUuidApplicationsRouteWithChildren
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/reports': typeof WorkspacesWorkspaceUuidReportsRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/workspaces/rp-registration-adoption/$rpApplicationUuid': typeof WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/invitations/rp-applications/': typeof InvitationsRpApplicationsIndexRoute
  '/workspaces/$workspaceUuid/': typeof WorkspacesWorkspaceUuidIndexRoute
  '/workspaces/rp-registration-adoption/': typeof WorkspacesRpRegistrationAdoptionIndexRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/applications/new': typeof WorkspacesWorkspaceUuidApplicationsNewRoute
  '/workspaces/$workspaceUuid/application-information/': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/applications/': typeof WorkspacesWorkspaceUuidApplicationsIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute
  '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation': typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/administration'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/invitations'
    | '/logout'
    | '/onboarding-oversight'
    | '/policies'
    | '/reports'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/workspaces'
    | '/your-applications'
    | '/invitations/rp-applications'
    | '/onboarding-oversight/queue'
    | '/onboarding-oversight/reports'
    | '/profile/setup'
    | '/reports/applications'
    | '/reports/workspaces'
    | '/users/$userUuid'
    | '/users/invite'
    | '/workspaces/$workspaceUuid'
    | '/workspaces/new'
    | '/workspaces/rp-registration-adoption'
    | '/your-applications/$rpApplicationUuid'
    | '/onboarding-oversight/'
    | '/reports/'
    | '/users/'
    | '/workspaces/'
    | '/your-applications/'
    | '/invitations/rp-applications/$token'
    | '/workspaces/$workspaceUuid/access'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/applications'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/reports'
    | '/workspaces/$workspaceUuid/settings'
    | '/workspaces/rp-registration-adoption/$rpApplicationUuid'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/invitations/rp-applications/'
    | '/workspaces/$workspaceUuid/'
    | '/workspaces/rp-registration-adoption/'
    | '/your-applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
    | '/workspaces/$workspaceUuid/applications/new'
    | '/workspaces/$workspaceUuid/application-information/'
    | '/workspaces/$workspaceUuid/applications/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/administration'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/invitations'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/onboarding-oversight/queue'
    | '/onboarding-oversight/reports'
    | '/profile/setup'
    | '/reports/applications'
    | '/reports/workspaces'
    | '/users/$userUuid'
    | '/users/invite'
    | '/workspaces/new'
    | '/onboarding-oversight'
    | '/reports'
    | '/users'
    | '/workspaces'
    | '/your-applications'
    | '/invitations/rp-applications/$token'
    | '/workspaces/$workspaceUuid/access'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/reports'
    | '/workspaces/$workspaceUuid/settings'
    | '/workspaces/rp-registration-adoption/$rpApplicationUuid'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/invitations/rp-applications'
    | '/workspaces/$workspaceUuid'
    | '/workspaces/rp-registration-adoption'
    | '/your-applications/$rpApplicationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/applications/new'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/applications'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/administration'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/invitations'
    | '/logout'
    | '/onboarding-oversight'
    | '/policies'
    | '/reports'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/workspaces'
    | '/your-applications'
    | '/invitations/rp-applications'
    | '/onboarding-oversight/queue'
    | '/onboarding-oversight/reports'
    | '/profile/setup'
    | '/reports/applications'
    | '/reports/workspaces'
    | '/users/$userUuid'
    | '/users/invite'
    | '/workspaces/$workspaceUuid'
    | '/workspaces/new'
    | '/workspaces/rp-registration-adoption'
    | '/your-applications/$rpApplicationUuid'
    | '/onboarding-oversight/'
    | '/reports/'
    | '/users/'
    | '/workspaces/'
    | '/your-applications/'
    | '/invitations/rp-applications/$token'
    | '/workspaces/$workspaceUuid/access'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/applications'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/reports'
    | '/workspaces/$workspaceUuid/settings'
    | '/workspaces/rp-registration-adoption/$rpApplicationUuid'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/invitations/rp-applications/'
    | '/workspaces/$workspaceUuid/'
    | '/workspaces/rp-registration-adoption/'
    | '/your-applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
    | '/workspaces/$workspaceUuid/applications/new'
    | '/workspaces/$workspaceUuid/application-information/'
    | '/workspaces/$workspaceUuid/applications/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'
    | '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdministrationRoute: typeof AdministrationRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ErrorRoute: typeof ErrorRoute
  InvitationsRoute: typeof InvitationsRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  OnboardingOversightRoute: typeof OnboardingOversightRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RolesRoute: typeof RolesRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TiersRoute: typeof TiersRoute
  UsersRoute: typeof UsersRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  YourApplicationsRoute: typeof YourApplicationsRouteWithChildren
  ProfileSetupRoute: typeof ProfileSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-applications': {
      id: '/your-applications'
      path: '/your-applications'
      fullPath: '/your-applications'
      preLoaderRoute: typeof YourApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-oversight': {
      id: '/onboarding-oversight'
      path: '/onboarding-oversight'
      fullPath: '/onboarding-oversight'
      preLoaderRoute: typeof OnboardingOversightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete': {
      id: '/auth-complete'
      path: '/auth-complete'
      fullPath: '/auth-complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-applications/': {
      id: '/your-applications/'
      path: '/'
      fullPath: '/your-applications/'
      preLoaderRoute: typeof YourApplicationsIndexRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/onboarding-oversight/': {
      id: '/onboarding-oversight/'
      path: '/'
      fullPath: '/onboarding-oversight/'
      preLoaderRoute: typeof OnboardingOversightIndexRouteImport
      parentRoute: typeof OnboardingOversightRoute
    }
    '/your-applications/$rpApplicationUuid': {
      id: '/your-applications/$rpApplicationUuid'
      path: '/$rpApplicationUuid'
      fullPath: '/your-applications/$rpApplicationUuid'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/workspaces/rp-registration-adoption': {
      id: '/workspaces/rp-registration-adoption'
      path: '/rp-registration-adoption'
      fullPath: '/workspaces/rp-registration-adoption'
      preLoaderRoute: typeof WorkspacesRpRegistrationAdoptionRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceUuid': {
      id: '/workspaces/$workspaceUuid'
      path: '/$workspaceUuid'
      fullPath: '/workspaces/$workspaceUuid'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/users/invite': {
      id: '/users/invite'
      path: '/invite'
      fullPath: '/users/invite'
      preLoaderRoute: typeof UsersInviteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$userUuid': {
      id: '/users/$userUuid'
      path: '/$userUuid'
      fullPath: '/users/$userUuid'
      preLoaderRoute: typeof UsersUserUuidRouteImport
      parentRoute: typeof UsersRoute
    }
    '/reports/workspaces': {
      id: '/reports/workspaces'
      path: '/workspaces'
      fullPath: '/reports/workspaces'
      preLoaderRoute: typeof ReportsWorkspacesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/applications': {
      id: '/reports/applications'
      path: '/applications'
      fullPath: '/reports/applications'
      preLoaderRoute: typeof ReportsApplicationsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-oversight/reports': {
      id: '/onboarding-oversight/reports'
      path: '/reports'
      fullPath: '/onboarding-oversight/reports'
      preLoaderRoute: typeof OnboardingOversightReportsRouteImport
      parentRoute: typeof OnboardingOversightRoute
    }
    '/onboarding-oversight/queue': {
      id: '/onboarding-oversight/queue'
      path: '/queue'
      fullPath: '/onboarding-oversight/queue'
      preLoaderRoute: typeof OnboardingOversightQueueRouteImport
      parentRoute: typeof OnboardingOversightRoute
    }
    '/invitations/rp-applications': {
      id: '/invitations/rp-applications'
      path: '/rp-applications'
      fullPath: '/invitations/rp-applications'
      preLoaderRoute: typeof InvitationsRpApplicationsRouteImport
      parentRoute: typeof InvitationsRoute
    }
    '/your-applications/$rpApplicationUuid/': {
      id: '/your-applications/$rpApplicationUuid/'
      path: '/'
      fullPath: '/your-applications/$rpApplicationUuid/'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidIndexRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/workspaces/rp-registration-adoption/': {
      id: '/workspaces/rp-registration-adoption/'
      path: '/'
      fullPath: '/workspaces/rp-registration-adoption/'
      preLoaderRoute: typeof WorkspacesRpRegistrationAdoptionIndexRouteImport
      parentRoute: typeof WorkspacesRpRegistrationAdoptionRoute
    }
    '/workspaces/$workspaceUuid/': {
      id: '/workspaces/$workspaceUuid/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/invitations/rp-applications/': {
      id: '/invitations/rp-applications/'
      path: '/'
      fullPath: '/invitations/rp-applications/'
      preLoaderRoute: typeof InvitationsRpApplicationsIndexRouteImport
      parentRoute: typeof InvitationsRpApplicationsRoute
    }
    '/your-applications/$rpApplicationUuid/mau-report': {
      id: '/your-applications/$rpApplicationUuid/mau-report'
      path: '/mau-report'
      fullPath: '/your-applications/$rpApplicationUuid/mau-report'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidMauReportRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/manage-credentials': {
      id: '/your-applications/$rpApplicationUuid/manage-credentials'
      path: '/manage-credentials'
      fullPath: '/your-applications/$rpApplicationUuid/manage-credentials'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/department-setup': {
      id: '/your-applications/$rpApplicationUuid/department-setup'
      path: '/department-setup'
      fullPath: '/your-applications/$rpApplicationUuid/department-setup'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/workspaces/rp-registration-adoption/$rpApplicationUuid': {
      id: '/workspaces/rp-registration-adoption/$rpApplicationUuid'
      path: '/$rpApplicationUuid'
      fullPath: '/workspaces/rp-registration-adoption/$rpApplicationUuid'
      preLoaderRoute: typeof WorkspacesRpRegistrationAdoptionRpApplicationUuidRouteImport
      parentRoute: typeof WorkspacesRpRegistrationAdoptionRoute
    }
    '/workspaces/$workspaceUuid/settings': {
      id: '/workspaces/$workspaceUuid/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceUuid/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidSettingsRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/reports': {
      id: '/workspaces/$workspaceUuid/reports'
      path: '/reports'
      fullPath: '/workspaces/$workspaceUuid/reports'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidReportsRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/members': {
      id: '/workspaces/$workspaceUuid/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceUuid/members'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidMembersRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/applications': {
      id: '/workspaces/$workspaceUuid/applications'
      path: '/applications'
      fullPath: '/workspaces/$workspaceUuid/applications'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information': {
      id: '/workspaces/$workspaceUuid/application-information'
      path: '/application-information'
      fullPath: '/workspaces/$workspaceUuid/application-information'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/access': {
      id: '/workspaces/$workspaceUuid/access'
      path: '/access'
      fullPath: '/workspaces/$workspaceUuid/access'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidAccessRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/invitations/rp-applications/$token': {
      id: '/invitations/rp-applications/$token'
      path: '/$token'
      fullPath: '/invitations/rp-applications/$token'
      preLoaderRoute: typeof InvitationsRpApplicationsTokenRouteImport
      parentRoute: typeof InvitationsRpApplicationsRoute
    }
    '/workspaces/$workspaceUuid/applications/': {
      id: '/workspaces/$workspaceUuid/applications/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/applications/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRoute
    }
    '/workspaces/$workspaceUuid/application-information/': {
      id: '/workspaces/$workspaceUuid/application-information/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/application-information/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/applications/new': {
      id: '/workspaces/$workspaceUuid/applications/new'
      path: '/new'
      fullPath: '/workspaces/$workspaceUuid/applications/new'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsNewRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
      path: '/$rpApplicationUuid'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRoute
    }
    '/workspaces/$workspaceUuid/application-information/new': {
      id: '/workspaces/$workspaceUuid/application-information/new'
      path: '/new'
      fullPath: '/workspaces/$workspaceUuid/application-information/new'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationNewRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
      path: '/$applicationInformationUuid'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
      path: '/usage'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/usage'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
      path: '/manage-credentials'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/manage-credentials'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
      path: '/edit'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/edit'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
      path: '/configuration'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/configuration'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
      path: '/audit'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/audit'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
      path: '/edit'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
      path: '/registration/confirmation'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/confirmation'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step': {
      id: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'
      path: '/registration/$step'
      fullPath: '/workspaces/$workspaceUuid/applications/$rpApplicationUuid/registration/$step'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute
    }
  }
}

interface InvitationsRpApplicationsRouteChildren {
  InvitationsRpApplicationsTokenRoute: typeof InvitationsRpApplicationsTokenRoute
  InvitationsRpApplicationsIndexRoute: typeof InvitationsRpApplicationsIndexRoute
}

const InvitationsRpApplicationsRouteChildren: InvitationsRpApplicationsRouteChildren =
  {
    InvitationsRpApplicationsTokenRoute: InvitationsRpApplicationsTokenRoute,
    InvitationsRpApplicationsIndexRoute: InvitationsRpApplicationsIndexRoute,
  }

const InvitationsRpApplicationsRouteWithChildren =
  InvitationsRpApplicationsRoute._addFileChildren(
    InvitationsRpApplicationsRouteChildren,
  )

interface InvitationsRouteChildren {
  InvitationsRpApplicationsRoute: typeof InvitationsRpApplicationsRouteWithChildren
}

const InvitationsRouteChildren: InvitationsRouteChildren = {
  InvitationsRpApplicationsRoute: InvitationsRpApplicationsRouteWithChildren,
}

const InvitationsRouteWithChildren = InvitationsRoute._addFileChildren(
  InvitationsRouteChildren,
)

interface OnboardingOversightRouteChildren {
  OnboardingOversightQueueRoute: typeof OnboardingOversightQueueRoute
  OnboardingOversightReportsRoute: typeof OnboardingOversightReportsRoute
  OnboardingOversightIndexRoute: typeof OnboardingOversightIndexRoute
}

const OnboardingOversightRouteChildren: OnboardingOversightRouteChildren = {
  OnboardingOversightQueueRoute: OnboardingOversightQueueRoute,
  OnboardingOversightReportsRoute: OnboardingOversightReportsRoute,
  OnboardingOversightIndexRoute: OnboardingOversightIndexRoute,
}

const OnboardingOversightRouteWithChildren =
  OnboardingOversightRoute._addFileChildren(OnboardingOversightRouteChildren)

interface ReportsRouteChildren {
  ReportsApplicationsRoute: typeof ReportsApplicationsRoute
  ReportsWorkspacesRoute: typeof ReportsWorkspacesRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsApplicationsRoute: ReportsApplicationsRoute,
  ReportsWorkspacesRoute: ReportsWorkspacesRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface UsersRouteChildren {
  UsersUserUuidRoute: typeof UsersUserUuidRoute
  UsersInviteRoute: typeof UsersInviteRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserUuidRoute: UsersUserUuidRoute,
  UsersInviteRoute: UsersInviteRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren {
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
}

const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren: WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute,
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute,
  }

const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren,
  )

interface WorkspacesWorkspaceUuidApplicationInformationRouteChildren {
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  WorkspacesWorkspaceUuidApplicationInformationNewRoute: typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  WorkspacesWorkspaceUuidApplicationInformationIndexRoute: typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
}

const WorkspacesWorkspaceUuidApplicationInformationRouteChildren: WorkspacesWorkspaceUuidApplicationInformationRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren,
    WorkspacesWorkspaceUuidApplicationInformationNewRoute:
      WorkspacesWorkspaceUuidApplicationInformationNewRoute,
    WorkspacesWorkspaceUuidApplicationInformationIndexRoute:
      WorkspacesWorkspaceUuidApplicationInformationIndexRoute,
  }

const WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationInformationRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationInformationRouteChildren,
  )

interface WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteChildren {
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute
}

const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteChildren: WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidAuditRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidConfigurationRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidEditRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidManageCredentialsRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidUsageRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidIndexRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationStepRoute,
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRegistrationConfirmationRoute,
  }

const WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteChildren,
  )

interface WorkspacesWorkspaceUuidApplicationsRouteChildren {
  WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute: typeof WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteWithChildren
  WorkspacesWorkspaceUuidApplicationsNewRoute: typeof WorkspacesWorkspaceUuidApplicationsNewRoute
  WorkspacesWorkspaceUuidApplicationsIndexRoute: typeof WorkspacesWorkspaceUuidApplicationsIndexRoute
}

const WorkspacesWorkspaceUuidApplicationsRouteChildren: WorkspacesWorkspaceUuidApplicationsRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRoute:
      WorkspacesWorkspaceUuidApplicationsRpApplicationUuidRouteWithChildren,
    WorkspacesWorkspaceUuidApplicationsNewRoute:
      WorkspacesWorkspaceUuidApplicationsNewRoute,
    WorkspacesWorkspaceUuidApplicationsIndexRoute:
      WorkspacesWorkspaceUuidApplicationsIndexRoute,
  }

const WorkspacesWorkspaceUuidApplicationsRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationsRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationsRouteChildren,
  )

interface WorkspacesWorkspaceUuidRouteChildren {
  WorkspacesWorkspaceUuidAccessRoute: typeof WorkspacesWorkspaceUuidAccessRoute
  WorkspacesWorkspaceUuidApplicationInformationRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  WorkspacesWorkspaceUuidApplicationsRoute: typeof WorkspacesWorkspaceUuidApplicationsRouteWithChildren
  WorkspacesWorkspaceUuidMembersRoute: typeof WorkspacesWorkspaceUuidMembersRoute
  WorkspacesWorkspaceUuidReportsRoute: typeof WorkspacesWorkspaceUuidReportsRoute
  WorkspacesWorkspaceUuidSettingsRoute: typeof WorkspacesWorkspaceUuidSettingsRoute
  WorkspacesWorkspaceUuidIndexRoute: typeof WorkspacesWorkspaceUuidIndexRoute
}

const WorkspacesWorkspaceUuidRouteChildren: WorkspacesWorkspaceUuidRouteChildren =
  {
    WorkspacesWorkspaceUuidAccessRoute: WorkspacesWorkspaceUuidAccessRoute,
    WorkspacesWorkspaceUuidApplicationInformationRoute:
      WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren,
    WorkspacesWorkspaceUuidApplicationsRoute:
      WorkspacesWorkspaceUuidApplicationsRouteWithChildren,
    WorkspacesWorkspaceUuidMembersRoute: WorkspacesWorkspaceUuidMembersRoute,
    WorkspacesWorkspaceUuidReportsRoute: WorkspacesWorkspaceUuidReportsRoute,
    WorkspacesWorkspaceUuidSettingsRoute: WorkspacesWorkspaceUuidSettingsRoute,
    WorkspacesWorkspaceUuidIndexRoute: WorkspacesWorkspaceUuidIndexRoute,
  }

const WorkspacesWorkspaceUuidRouteWithChildren =
  WorkspacesWorkspaceUuidRoute._addFileChildren(
    WorkspacesWorkspaceUuidRouteChildren,
  )

interface WorkspacesRpRegistrationAdoptionRouteChildren {
  WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute: typeof WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute
  WorkspacesRpRegistrationAdoptionIndexRoute: typeof WorkspacesRpRegistrationAdoptionIndexRoute
}

const WorkspacesRpRegistrationAdoptionRouteChildren: WorkspacesRpRegistrationAdoptionRouteChildren =
  {
    WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute:
      WorkspacesRpRegistrationAdoptionRpApplicationUuidRoute,
    WorkspacesRpRegistrationAdoptionIndexRoute:
      WorkspacesRpRegistrationAdoptionIndexRoute,
  }

const WorkspacesRpRegistrationAdoptionRouteWithChildren =
  WorkspacesRpRegistrationAdoptionRoute._addFileChildren(
    WorkspacesRpRegistrationAdoptionRouteChildren,
  )

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceUuidRoute: typeof WorkspacesWorkspaceUuidRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesRpRegistrationAdoptionRoute: typeof WorkspacesRpRegistrationAdoptionRouteWithChildren
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceUuidRoute: WorkspacesWorkspaceUuidRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesRpRegistrationAdoptionRoute:
    WorkspacesRpRegistrationAdoptionRouteWithChildren,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

interface YourApplicationsRpApplicationUuidRouteChildren {
  YourApplicationsRpApplicationUuidDepartmentSetupRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  YourApplicationsRpApplicationUuidManageCredentialsRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  YourApplicationsRpApplicationUuidMauReportRoute: typeof YourApplicationsRpApplicationUuidMauReportRoute
  YourApplicationsRpApplicationUuidIndexRoute: typeof YourApplicationsRpApplicationUuidIndexRoute
}

const YourApplicationsRpApplicationUuidRouteChildren: YourApplicationsRpApplicationUuidRouteChildren =
  {
    YourApplicationsRpApplicationUuidDepartmentSetupRoute:
      YourApplicationsRpApplicationUuidDepartmentSetupRoute,
    YourApplicationsRpApplicationUuidManageCredentialsRoute:
      YourApplicationsRpApplicationUuidManageCredentialsRoute,
    YourApplicationsRpApplicationUuidMauReportRoute:
      YourApplicationsRpApplicationUuidMauReportRoute,
    YourApplicationsRpApplicationUuidIndexRoute:
      YourApplicationsRpApplicationUuidIndexRoute,
  }

const YourApplicationsRpApplicationUuidRouteWithChildren =
  YourApplicationsRpApplicationUuidRoute._addFileChildren(
    YourApplicationsRpApplicationUuidRouteChildren,
  )

interface YourApplicationsRouteChildren {
  YourApplicationsRpApplicationUuidRoute: typeof YourApplicationsRpApplicationUuidRouteWithChildren
  YourApplicationsIndexRoute: typeof YourApplicationsIndexRoute
}

const YourApplicationsRouteChildren: YourApplicationsRouteChildren = {
  YourApplicationsRpApplicationUuidRoute:
    YourApplicationsRpApplicationUuidRouteWithChildren,
  YourApplicationsIndexRoute: YourApplicationsIndexRoute,
}

const YourApplicationsRouteWithChildren =
  YourApplicationsRoute._addFileChildren(YourApplicationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdministrationRoute: AdministrationRoute,
  AuditLogsRoute: AuditLogsRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  DepartmentsRoute: DepartmentsRoute,
  ErrorRoute: ErrorRoute,
  InvitationsRoute: InvitationsRouteWithChildren,
  LogoutRoute: LogoutRoute,
  OnboardingOversightRoute: OnboardingOversightRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RolesRoute: RolesRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TiersRoute: TiersRoute,
  UsersRoute: UsersRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  YourApplicationsRoute: YourApplicationsRouteWithChildren,
  ProfileSetupRoute: ProfileSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
