/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourApplicationsRouteImport } from './routes/your-applications'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AuthCompleteRouteImport } from './routes/auth-complete'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YourApplicationsIndexRouteImport } from './routes/your-applications/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as YourApplicationsRpApplicationUuidRouteImport } from './routes/your-applications/$rpApplicationUuid'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WorkspacesWorkspaceUuidRouteImport } from './routes/workspaces/$workspaceUuid'
import { Route as ProfileSetupRouteImport } from './routes/profile/setup'
import { Route as YourApplicationsRpApplicationUuidIndexRouteImport } from './routes/your-applications/$rpApplicationUuid/index'
import { Route as WorkspacesWorkspaceUuidIndexRouteImport } from './routes/workspaces/$workspaceUuid/index'
import { Route as YourApplicationsRpApplicationUuidMauReportRouteImport } from './routes/your-applications/$rpApplicationUuid/mau-report'
import { Route as YourApplicationsRpApplicationUuidManageCredentialsRouteImport } from './routes/your-applications/$rpApplicationUuid/manage-credentials'
import { Route as YourApplicationsRpApplicationUuidDepartmentSetupRouteImport } from './routes/your-applications/$rpApplicationUuid/department-setup'
import { Route as WorkspacesWorkspaceUuidSettingsRouteImport } from './routes/workspaces/$workspaceUuid/settings'
import { Route as WorkspacesWorkspaceUuidMembersRouteImport } from './routes/workspaces/$workspaceUuid/members'
import { Route as WorkspacesWorkspaceUuidApplicationInformationRouteImport } from './routes/workspaces/$workspaceUuid/application-information'
import { Route as WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport } from './routes/workspaces/$workspaceUuid/application-information/index'
import { Route as WorkspacesWorkspaceUuidApplicationInformationNewRouteImport } from './routes/workspaces/$workspaceUuid/application-information/new'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/index'
import { Route as WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport } from './routes/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'

const YourApplicationsRoute = YourApplicationsRouteImport.update({
  id: '/your-applications',
  path: '/your-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth-complete',
  path: '/auth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YourApplicationsIndexRoute = YourApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YourApplicationsRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const YourApplicationsRpApplicationUuidRoute =
  YourApplicationsRpApplicationUuidRouteImport.update({
    id: '/$rpApplicationUuid',
    path: '/$rpApplicationUuid',
    getParentRoute: () => YourApplicationsRoute,
  } as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceUuidRoute = WorkspacesWorkspaceUuidRouteImport.update({
  id: '/$workspaceUuid',
  path: '/$workspaceUuid',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const YourApplicationsRpApplicationUuidIndexRoute =
  YourApplicationsRpApplicationUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidIndexRoute =
  WorkspacesWorkspaceUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidMauReportRoute =
  YourApplicationsRpApplicationUuidMauReportRouteImport.update({
    id: '/mau-report',
    path: '/mau-report',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidManageCredentialsRoute =
  YourApplicationsRpApplicationUuidManageCredentialsRouteImport.update({
    id: '/manage-credentials',
    path: '/manage-credentials',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidDepartmentSetupRoute =
  YourApplicationsRpApplicationUuidDepartmentSetupRouteImport.update({
    id: '/department-setup',
    path: '/department-setup',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidSettingsRoute =
  WorkspacesWorkspaceUuidSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidMembersRoute =
  WorkspacesWorkspaceUuidMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationRoute =
  WorkspacesWorkspaceUuidApplicationInformationRouteImport.update({
    id: '/application-information',
    path: '/application-information',
    getParentRoute: () => WorkspacesWorkspaceUuidRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationIndexRoute =
  WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationNewRoute =
  WorkspacesWorkspaceUuidApplicationInformationNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
  } as any)
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport.update(
    {
      id: '/$applicationInformationUuid',
      path: '/$applicationInformationUuid',
      getParentRoute: () => WorkspacesWorkspaceUuidApplicationInformationRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute,
    } as any,
  )
const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/profile/setup': typeof ProfileSetupRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/workspaces/$workspaceUuid/': typeof WorkspacesWorkspaceUuidIndexRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/application-information/': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/your-applications': typeof YourApplicationsIndexRoute
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidIndexRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/profile/setup': typeof ProfileSetupRoute
  '/workspaces/$workspaceUuid': typeof WorkspacesWorkspaceUuidRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/workspaces/$workspaceUuid/application-information': typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  '/workspaces/$workspaceUuid/members': typeof WorkspacesWorkspaceUuidMembersRoute
  '/workspaces/$workspaceUuid/settings': typeof WorkspacesWorkspaceUuidSettingsRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/workspaces/$workspaceUuid/': typeof WorkspacesWorkspaceUuidIndexRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  '/workspaces/$workspaceUuid/application-information/new': typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  '/workspaces/$workspaceUuid/application-information/': typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/workspaces'
    | '/your-applications'
    | '/profile/setup'
    | '/workspaces/$workspaceUuid'
    | '/workspaces/new'
    | '/your-applications/$rpApplicationUuid'
    | '/workspaces/'
    | '/your-applications/'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/settings'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/workspaces/$workspaceUuid/'
    | '/your-applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/application-information/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/profile/setup'
    | '/workspaces/new'
    | '/workspaces'
    | '/your-applications'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/settings'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/workspaces/$workspaceUuid'
    | '/your-applications/$rpApplicationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/workspaces'
    | '/your-applications'
    | '/profile/setup'
    | '/workspaces/$workspaceUuid'
    | '/workspaces/new'
    | '/your-applications/$rpApplicationUuid'
    | '/workspaces/'
    | '/your-applications/'
    | '/workspaces/$workspaceUuid/application-information'
    | '/workspaces/$workspaceUuid/members'
    | '/workspaces/$workspaceUuid/settings'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/workspaces/$workspaceUuid/'
    | '/your-applications/$rpApplicationUuid/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
    | '/workspaces/$workspaceUuid/application-information/new'
    | '/workspaces/$workspaceUuid/application-information/'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
    | '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ErrorRoute: typeof ErrorRoute
  LogoutRoute: typeof LogoutRoute
  PoliciesRoute: typeof PoliciesRoute
  RolesRoute: typeof RolesRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TiersRoute: typeof TiersRoute
  UsersRoute: typeof UsersRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  YourApplicationsRoute: typeof YourApplicationsRouteWithChildren
  ProfileSetupRoute: typeof ProfileSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-applications': {
      id: '/your-applications'
      path: '/your-applications'
      fullPath: '/your-applications'
      preLoaderRoute: typeof YourApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete': {
      id: '/auth-complete'
      path: '/auth-complete'
      fullPath: '/auth-complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-applications/': {
      id: '/your-applications/'
      path: '/'
      fullPath: '/your-applications/'
      preLoaderRoute: typeof YourApplicationsIndexRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/your-applications/$rpApplicationUuid': {
      id: '/your-applications/$rpApplicationUuid'
      path: '/$rpApplicationUuid'
      fullPath: '/your-applications/$rpApplicationUuid'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceUuid': {
      id: '/workspaces/$workspaceUuid'
      path: '/$workspaceUuid'
      fullPath: '/workspaces/$workspaceUuid'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-applications/$rpApplicationUuid/': {
      id: '/your-applications/$rpApplicationUuid/'
      path: '/'
      fullPath: '/your-applications/$rpApplicationUuid/'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidIndexRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/': {
      id: '/workspaces/$workspaceUuid/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/your-applications/$rpApplicationUuid/mau-report': {
      id: '/your-applications/$rpApplicationUuid/mau-report'
      path: '/mau-report'
      fullPath: '/your-applications/$rpApplicationUuid/mau-report'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidMauReportRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/manage-credentials': {
      id: '/your-applications/$rpApplicationUuid/manage-credentials'
      path: '/manage-credentials'
      fullPath: '/your-applications/$rpApplicationUuid/manage-credentials'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/department-setup': {
      id: '/your-applications/$rpApplicationUuid/department-setup'
      path: '/department-setup'
      fullPath: '/your-applications/$rpApplicationUuid/department-setup'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/workspaces/$workspaceUuid/settings': {
      id: '/workspaces/$workspaceUuid/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceUuid/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidSettingsRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/members': {
      id: '/workspaces/$workspaceUuid/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceUuid/members'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidMembersRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information': {
      id: '/workspaces/$workspaceUuid/application-information'
      path: '/application-information'
      fullPath: '/workspaces/$workspaceUuid/application-information'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information/': {
      id: '/workspaces/$workspaceUuid/application-information/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/application-information/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/application-information/new': {
      id: '/workspaces/$workspaceUuid/application-information/new'
      path: '/new'
      fullPath: '/workspaces/$workspaceUuid/application-information/new'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationNewRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
      path: '/$applicationInformationUuid'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
      path: '/'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute
    }
    '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit': {
      id: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
      path: '/edit'
      fullPath: '/workspaces/$workspaceUuid/application-information/$applicationInformationUuid/edit'
      preLoaderRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRouteImport
      parentRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute
    }
  }
}

interface WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren {
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute
}

const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren: WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidEditRoute,
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidIndexRoute,
  }

const WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteChildren,
  )

interface WorkspacesWorkspaceUuidApplicationInformationRouteChildren {
  WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute: typeof WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren
  WorkspacesWorkspaceUuidApplicationInformationNewRoute: typeof WorkspacesWorkspaceUuidApplicationInformationNewRoute
  WorkspacesWorkspaceUuidApplicationInformationIndexRoute: typeof WorkspacesWorkspaceUuidApplicationInformationIndexRoute
}

const WorkspacesWorkspaceUuidApplicationInformationRouteChildren: WorkspacesWorkspaceUuidApplicationInformationRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRoute:
      WorkspacesWorkspaceUuidApplicationInformationApplicationInformationUuidRouteWithChildren,
    WorkspacesWorkspaceUuidApplicationInformationNewRoute:
      WorkspacesWorkspaceUuidApplicationInformationNewRoute,
    WorkspacesWorkspaceUuidApplicationInformationIndexRoute:
      WorkspacesWorkspaceUuidApplicationInformationIndexRoute,
  }

const WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren =
  WorkspacesWorkspaceUuidApplicationInformationRoute._addFileChildren(
    WorkspacesWorkspaceUuidApplicationInformationRouteChildren,
  )

interface WorkspacesWorkspaceUuidRouteChildren {
  WorkspacesWorkspaceUuidApplicationInformationRoute: typeof WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren
  WorkspacesWorkspaceUuidMembersRoute: typeof WorkspacesWorkspaceUuidMembersRoute
  WorkspacesWorkspaceUuidSettingsRoute: typeof WorkspacesWorkspaceUuidSettingsRoute
  WorkspacesWorkspaceUuidIndexRoute: typeof WorkspacesWorkspaceUuidIndexRoute
}

const WorkspacesWorkspaceUuidRouteChildren: WorkspacesWorkspaceUuidRouteChildren =
  {
    WorkspacesWorkspaceUuidApplicationInformationRoute:
      WorkspacesWorkspaceUuidApplicationInformationRouteWithChildren,
    WorkspacesWorkspaceUuidMembersRoute: WorkspacesWorkspaceUuidMembersRoute,
    WorkspacesWorkspaceUuidSettingsRoute: WorkspacesWorkspaceUuidSettingsRoute,
    WorkspacesWorkspaceUuidIndexRoute: WorkspacesWorkspaceUuidIndexRoute,
  }

const WorkspacesWorkspaceUuidRouteWithChildren =
  WorkspacesWorkspaceUuidRoute._addFileChildren(
    WorkspacesWorkspaceUuidRouteChildren,
  )

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceUuidRoute: typeof WorkspacesWorkspaceUuidRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceUuidRoute: WorkspacesWorkspaceUuidRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

interface YourApplicationsRpApplicationUuidRouteChildren {
  YourApplicationsRpApplicationUuidDepartmentSetupRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  YourApplicationsRpApplicationUuidManageCredentialsRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  YourApplicationsRpApplicationUuidMauReportRoute: typeof YourApplicationsRpApplicationUuidMauReportRoute
  YourApplicationsRpApplicationUuidIndexRoute: typeof YourApplicationsRpApplicationUuidIndexRoute
}

const YourApplicationsRpApplicationUuidRouteChildren: YourApplicationsRpApplicationUuidRouteChildren =
  {
    YourApplicationsRpApplicationUuidDepartmentSetupRoute:
      YourApplicationsRpApplicationUuidDepartmentSetupRoute,
    YourApplicationsRpApplicationUuidManageCredentialsRoute:
      YourApplicationsRpApplicationUuidManageCredentialsRoute,
    YourApplicationsRpApplicationUuidMauReportRoute:
      YourApplicationsRpApplicationUuidMauReportRoute,
    YourApplicationsRpApplicationUuidIndexRoute:
      YourApplicationsRpApplicationUuidIndexRoute,
  }

const YourApplicationsRpApplicationUuidRouteWithChildren =
  YourApplicationsRpApplicationUuidRoute._addFileChildren(
    YourApplicationsRpApplicationUuidRouteChildren,
  )

interface YourApplicationsRouteChildren {
  YourApplicationsRpApplicationUuidRoute: typeof YourApplicationsRpApplicationUuidRouteWithChildren
  YourApplicationsIndexRoute: typeof YourApplicationsIndexRoute
}

const YourApplicationsRouteChildren: YourApplicationsRouteChildren = {
  YourApplicationsRpApplicationUuidRoute:
    YourApplicationsRpApplicationUuidRouteWithChildren,
  YourApplicationsIndexRoute: YourApplicationsIndexRoute,
}

const YourApplicationsRouteWithChildren =
  YourApplicationsRoute._addFileChildren(YourApplicationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuditLogsRoute: AuditLogsRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  DepartmentsRoute: DepartmentsRoute,
  ErrorRoute: ErrorRoute,
  LogoutRoute: LogoutRoute,
  PoliciesRoute: PoliciesRoute,
  RolesRoute: RolesRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TiersRoute: TiersRoute,
  UsersRoute: UsersRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  YourApplicationsRoute: YourApplicationsRouteWithChildren,
  ProfileSetupRoute: ProfileSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
