/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourApplicationsRouteImport } from './routes/your-applications'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AuthCompleteRouteImport } from './routes/auth-complete'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YourApplicationsIndexRouteImport } from './routes/your-applications/index'
import { Route as YourApplicationsRpApplicationUuidRouteImport } from './routes/your-applications/$rpApplicationUuid'
import { Route as ProfileSetupRouteImport } from './routes/profile/setup'
import { Route as YourApplicationsRpApplicationUuidIndexRouteImport } from './routes/your-applications/$rpApplicationUuid/index'
import { Route as YourApplicationsRpApplicationUuidMauReportRouteImport } from './routes/your-applications/$rpApplicationUuid/mau-report'
import { Route as YourApplicationsRpApplicationUuidManageCredentialsRouteImport } from './routes/your-applications/$rpApplicationUuid/manage-credentials'
import { Route as YourApplicationsRpApplicationUuidDepartmentSetupRouteImport } from './routes/your-applications/$rpApplicationUuid/department-setup'

const YourApplicationsRoute = YourApplicationsRouteImport.update({
  id: '/your-applications',
  path: '/your-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth-complete',
  path: '/auth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YourApplicationsIndexRoute = YourApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YourApplicationsRoute,
} as any)
const YourApplicationsRpApplicationUuidRoute =
  YourApplicationsRpApplicationUuidRouteImport.update({
    id: '/$rpApplicationUuid',
    path: '/$rpApplicationUuid',
    getParentRoute: () => YourApplicationsRoute,
  } as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const YourApplicationsRpApplicationUuidIndexRoute =
  YourApplicationsRpApplicationUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidMauReportRoute =
  YourApplicationsRpApplicationUuidMauReportRouteImport.update({
    id: '/mau-report',
    path: '/mau-report',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidManageCredentialsRoute =
  YourApplicationsRpApplicationUuidManageCredentialsRouteImport.update({
    id: '/manage-credentials',
    path: '/manage-credentials',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)
const YourApplicationsRpApplicationUuidDepartmentSetupRoute =
  YourApplicationsRpApplicationUuidDepartmentSetupRouteImport.update({
    id: '/department-setup',
    path: '/department-setup',
    getParentRoute: () => YourApplicationsRpApplicationUuidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/profile/setup': typeof ProfileSetupRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/your-applications': typeof YourApplicationsIndexRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/departments': typeof DepartmentsRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/policies': typeof PoliciesRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
  '/your-applications': typeof YourApplicationsRouteWithChildren
  '/profile/setup': typeof ProfileSetupRoute
  '/your-applications/$rpApplicationUuid': typeof YourApplicationsRpApplicationUuidRouteWithChildren
  '/your-applications/': typeof YourApplicationsIndexRoute
  '/your-applications/$rpApplicationUuid/department-setup': typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  '/your-applications/$rpApplicationUuid/manage-credentials': typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  '/your-applications/$rpApplicationUuid/mau-report': typeof YourApplicationsRpApplicationUuidMauReportRoute
  '/your-applications/$rpApplicationUuid/': typeof YourApplicationsRpApplicationUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/your-applications'
    | '/profile/setup'
    | '/your-applications/$rpApplicationUuid'
    | '/your-applications/'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/your-applications/$rpApplicationUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/profile/setup'
    | '/your-applications'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/your-applications/$rpApplicationUuid'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/access-denied'
    | '/audit-logs'
    | '/auth-complete'
    | '/departments'
    | '/error'
    | '/logout'
    | '/policies'
    | '/roles'
    | '/support'
    | '/terms-and-conditions'
    | '/tiers'
    | '/users'
    | '/your-applications'
    | '/profile/setup'
    | '/your-applications/$rpApplicationUuid'
    | '/your-applications/'
    | '/your-applications/$rpApplicationUuid/department-setup'
    | '/your-applications/$rpApplicationUuid/manage-credentials'
    | '/your-applications/$rpApplicationUuid/mau-report'
    | '/your-applications/$rpApplicationUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ErrorRoute: typeof ErrorRoute
  LogoutRoute: typeof LogoutRoute
  PoliciesRoute: typeof PoliciesRoute
  RolesRoute: typeof RolesRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TiersRoute: typeof TiersRoute
  UsersRoute: typeof UsersRoute
  YourApplicationsRoute: typeof YourApplicationsRouteWithChildren
  ProfileSetupRoute: typeof ProfileSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-applications': {
      id: '/your-applications'
      path: '/your-applications'
      fullPath: '/your-applications'
      preLoaderRoute: typeof YourApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete': {
      id: '/auth-complete'
      path: '/auth-complete'
      fullPath: '/auth-complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-applications/': {
      id: '/your-applications/'
      path: '/'
      fullPath: '/your-applications/'
      preLoaderRoute: typeof YourApplicationsIndexRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/your-applications/$rpApplicationUuid': {
      id: '/your-applications/$rpApplicationUuid'
      path: '/$rpApplicationUuid'
      fullPath: '/your-applications/$rpApplicationUuid'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidRouteImport
      parentRoute: typeof YourApplicationsRoute
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-applications/$rpApplicationUuid/': {
      id: '/your-applications/$rpApplicationUuid/'
      path: '/'
      fullPath: '/your-applications/$rpApplicationUuid/'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidIndexRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/mau-report': {
      id: '/your-applications/$rpApplicationUuid/mau-report'
      path: '/mau-report'
      fullPath: '/your-applications/$rpApplicationUuid/mau-report'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidMauReportRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/manage-credentials': {
      id: '/your-applications/$rpApplicationUuid/manage-credentials'
      path: '/manage-credentials'
      fullPath: '/your-applications/$rpApplicationUuid/manage-credentials'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
    '/your-applications/$rpApplicationUuid/department-setup': {
      id: '/your-applications/$rpApplicationUuid/department-setup'
      path: '/department-setup'
      fullPath: '/your-applications/$rpApplicationUuid/department-setup'
      preLoaderRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRouteImport
      parentRoute: typeof YourApplicationsRpApplicationUuidRoute
    }
  }
}

interface YourApplicationsRpApplicationUuidRouteChildren {
  YourApplicationsRpApplicationUuidDepartmentSetupRoute: typeof YourApplicationsRpApplicationUuidDepartmentSetupRoute
  YourApplicationsRpApplicationUuidManageCredentialsRoute: typeof YourApplicationsRpApplicationUuidManageCredentialsRoute
  YourApplicationsRpApplicationUuidMauReportRoute: typeof YourApplicationsRpApplicationUuidMauReportRoute
  YourApplicationsRpApplicationUuidIndexRoute: typeof YourApplicationsRpApplicationUuidIndexRoute
}

const YourApplicationsRpApplicationUuidRouteChildren: YourApplicationsRpApplicationUuidRouteChildren =
  {
    YourApplicationsRpApplicationUuidDepartmentSetupRoute:
      YourApplicationsRpApplicationUuidDepartmentSetupRoute,
    YourApplicationsRpApplicationUuidManageCredentialsRoute:
      YourApplicationsRpApplicationUuidManageCredentialsRoute,
    YourApplicationsRpApplicationUuidMauReportRoute:
      YourApplicationsRpApplicationUuidMauReportRoute,
    YourApplicationsRpApplicationUuidIndexRoute:
      YourApplicationsRpApplicationUuidIndexRoute,
  }

const YourApplicationsRpApplicationUuidRouteWithChildren =
  YourApplicationsRpApplicationUuidRoute._addFileChildren(
    YourApplicationsRpApplicationUuidRouteChildren,
  )

interface YourApplicationsRouteChildren {
  YourApplicationsRpApplicationUuidRoute: typeof YourApplicationsRpApplicationUuidRouteWithChildren
  YourApplicationsIndexRoute: typeof YourApplicationsIndexRoute
}

const YourApplicationsRouteChildren: YourApplicationsRouteChildren = {
  YourApplicationsRpApplicationUuidRoute:
    YourApplicationsRpApplicationUuidRouteWithChildren,
  YourApplicationsIndexRoute: YourApplicationsIndexRoute,
}

const YourApplicationsRouteWithChildren =
  YourApplicationsRoute._addFileChildren(YourApplicationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuditLogsRoute: AuditLogsRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  DepartmentsRoute: DepartmentsRoute,
  ErrorRoute: ErrorRoute,
  LogoutRoute: LogoutRoute,
  PoliciesRoute: PoliciesRoute,
  RolesRoute: RolesRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TiersRoute: TiersRoute,
  UsersRoute: UsersRoute,
  YourApplicationsRoute: YourApplicationsRouteWithChildren,
  ProfileSetupRoute: ProfileSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
