#!/usr/bin/env bash
#
# sync-deploy-env.sh
#
# Generates deploy/terraform.tfvars from infra/ outputs.
# Run this after `terraform apply` in infra/ and before `terraform apply` in deploy/.
#
# Usage:
#   cd sample-aws-deploy/terraform
#   ./scripts/sync-deploy-env.sh
#
# This reads outputs from infra/ (via `terraform output -json`) and writes
# deploy/terraform.tfvars with all computed infrastructure references
# (RDS endpoint, ElastiCache endpoint, CloudFront URLs, secret ARNs, etc.).
#
# WARNING: This overwrites deploy/terraform.tfvars. Back it up if you have
# custom edits.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/../infra"
DEPLOY_DIR="$SCRIPT_DIR/../deploy"
OUTPUT_FILE="$DEPLOY_DIR/terraform.tfvars"

if [ ! -f "$INFRA_DIR/.terraform/terraform.tfstate" ]; then
  echo "ERROR: infra/ has not been applied yet. Run 'cd infra && terraform init && terraform apply' first."
  exit 1
fi

echo "=== Generating deploy/terraform.tfvars from infra outputs ==="

# Capture infra outputs as JSON
OUTPUTS=$(cd "$INFRA_DIR" && terraform output -json)

# Helper: extract a string value from the outputs JSON
extract() {
  echo "$OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['$1']['value'])"
}

# Helper: extract a list value from the outputs JSON
extract_list() {
  echo "$OUTPUTS" | python3 -c "import sys,json; v=json.load(sys.stdin)['$1']['value']; print(' '.join(v))"
}

# Build the tfvars file
cat > "$OUTPUT_FILE" << EOF
# Generated by sync-deploy-env.sh — DO NOT EDIT MANUALLY
# Re-run the script after Wave 1 (infra) changes.
aws_region                           = "$(extract aws_region)"
environment                          = "$(extract environment)"
app_name                             = "$(extract app_name)"

# ----- Infra computed values -----
ecs_cluster_id                       = "$(extract ecs_cluster_id)"
ecs_execution_role_arn               = "$(extract ecs_execution_role_arn)"
ecs_task_role_arn                    = "$(extract ecs_task_role_arn)"
target_group_arn                     = "$(extract target_group_arn)"
ecs_web_security_group_id            = "$(extract ecs_web_security_group_id)"
ecs_worker_security_group_id         = "$(extract ecs_worker_security_group_id)"
private_subnet_ids                   = [$(extract_list private_subnet_ids | sed 's/[^ ]*/"&"/g' | sed 's/ /, /g')]
ecr_repository_url                   = "$(extract ecr_repository_url)"
rds_endpoint                         = "$(extract rds_endpoint)"
rds_port                             = $(extract rds_port)
elasticache_endpoint                 = "$(extract elasticache_endpoint)"
frontend_url                         = "$(extract frontend_url)"
api_url                              = "$(extract api_url)"
mau_s3_bucket_name                   = "$(extract mau_s3_bucket_name)"
cloudwatch_log_group_web             = "$(extract cloudwatch_log_group_web)"
cloudwatch_log_group_worker          = "$(extract cloudwatch_log_group_worker)"

# ----- Secrets -----
db_password_secret_arn               = "$(extract db_password_secret_arn)"
oidc_client_secret_arn               = "$(extract oidc_client_secret_arn)"
ibm_sv_admin_client_secret_arn       = "$(extract ibm_sv_admin_client_secret_arn)"
session_secret_arn                   = "$(extract session_secret_arn)"
redis_password_secret_arn            = "$(extract redis_password_secret_arn)"

# ----- Redis TLS (must match infra/elasticache.tf transit_encryption_enabled) -----
redis_session_ssl                    = true
redis_cache_ssl                      = true
redis_queue_ssl                      = true
redis_rate_limit_ssl                 = true
EOF

echo "=== Done! Written to: $OUTPUT_FILE ==="
echo ""
echo "You can now run: cd deploy && terraform init && terraform apply"
